### ISSUE TITLE
inherited font sizes

### ISSUE THREAD

**Issue by ryanseddon** [suitcss/components-grid#25]
Maybe I'm not thinking about this correctly but I have a base font size:

``` css
html {
  font-size: 10px;
}
body {
  font-size: 1.3rem;
}
```

Because `.Grid-cell` has `font-size: 1rem` it sets everything to 10px how can I have a nicer way for it to inherit my base font sizing?
